# Generated by Django 5.1 on 2024-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart_app', '0003_remove_cartitem_product_name_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
