# Generated by Django 5.1 on 2024-10-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart_app', '0005_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
