# Generated by Django 5.1 on 2024-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart_app', '0006_remove_wishlistitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/fruits/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
