# Generated by Django 5.1 on 2024-10-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart_app', '0008_cartitem_fruit_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='fruit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freshcart_app.fruits'),
            preserve_default=False,
        ),
    ]
