# Generated by Django 5.1 on 2024-10-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart_app', '0011_dairy_cartitem_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='dairy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freshcart_app.dairy'),
        ),
    ]
